### ============================================
### ADD EXPERIENCE DATA
### ============================================

### Experience 1 - VOR Developers
POST https://my-portfolio-chi-five-uhj0jqhcn2.vercel.app/api/experience
Content-Type: application/json

{
    "position": "Admin & IT Support",
    "company": "VOR DEVELOPERS PRIVATE LIMITED",
    "duration": "2022-2026",
    "description": "Developing responsive and modern web interfaces using React.js, JavaScript, HTML and CSS. Working on reusable components and improving user experience.",
    "order": 1
}

### Experience 2 - Ufone Center
POST https://my-portfolio-chi-five-uhj0jqhcn2.vercel.app/api/experience
Content-Type: application/json

{
    "position": "IT Support & CSR",
    "company": "Ufone Center",
    "duration": "2020-2021",
    "description": "IT Assistant & Customer Service Representative",
    "order": 2
}

### Experience 3 - Vector3 Solutions
POST https://my-portfolio-chi-five-uhj0jqhcn2.vercel.app/api/experience
Content-Type: application/json

{
    "position": "Game Developer",
    "company": "Vector3 Solutions",
    "duration": "2016-2017",
    "description": "IT Assistant & Customer Service Representative",
    "order": 3
}

### Get all experience
GET https://my-portfolio-chi-five-uhj0jqhcn2.vercel.app/api/experience